bot_token: ODc5NzY5NTYxMjM3NDIyMTQw.YSUjQA.6w9WoP59oSywvILXLC4mk_Ff884
osu_client_id: 9150
osu_client_secret: VNf5bhOtw8pxnubkO0dzxeFglfibZWZOtfxzIK24
unsplash_api_key: Anrk4njhlgKYtZNtoNOfocxwcii0hhnhZHpjMr0oE18ggit it